/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__hspace = 1,
  sym__newline = 2,
  sym_comment = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  sym__atom = 6,
  sym_single_quoted_string = 7,
  sym_double_quoted_string = 8,
  sym_source_file = 9,
  sym__leading_spacing = 10,
  aux_sym__spacing = 11,
  sym__space_unit = 12,
  sym__line_break = 13,
  sym_rule = 14,
  sym__rule_body = 15,
  sym__value = 16,
  sym_rule_name = 17,
  sym_literal = 18,
  aux_sym_source_file_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__hspace] = "_hspace",
  [sym__newline] = "_newline",
  [sym_comment] = "comment",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym__atom] = "_atom",
  [sym_single_quoted_string] = "single_quoted_string",
  [sym_double_quoted_string] = "double_quoted_string",
  [sym_source_file] = "source_file",
  [sym__leading_spacing] = "_leading_spacing",
  [aux_sym__spacing] = "_spacing",
  [sym__space_unit] = "_space_unit",
  [sym__line_break] = "_line_break",
  [sym_rule] = "rule",
  [sym__rule_body] = "_rule_body",
  [sym__value] = "_value",
  [sym_rule_name] = "rule_name",
  [sym_literal] = "literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__hspace] = sym__hspace,
  [sym__newline] = sym__newline,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__atom] = sym__atom,
  [sym_single_quoted_string] = sym_single_quoted_string,
  [sym_double_quoted_string] = sym_double_quoted_string,
  [sym_source_file] = sym_source_file,
  [sym__leading_spacing] = sym__leading_spacing,
  [aux_sym__spacing] = aux_sym__spacing,
  [sym__space_unit] = sym__space_unit,
  [sym__line_break] = sym__line_break,
  [sym_rule] = sym_rule,
  [sym__rule_body] = sym__rule_body,
  [sym__value] = sym__value,
  [sym_rule_name] = sym_rule_name,
  [sym_literal] = sym_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__hspace] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_single_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__leading_spacing] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__spacing] = {
    .visible = false,
    .named = false,
  },
  [sym__space_unit] = {
    .visible = false,
    .named = true,
  },
  [sym__line_break] = {
    .visible = false,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym__rule_body] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_rule_name] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_body, 0},
  [2] =
    {field_body, 2, .inherited = true},
    {field_name, 0},
  [4] =
    {field_body, 3, .inherited = true},
    {field_name, 0},
  [6] =
    {field_body, 0},
    {field_body, 2, .inherited = true},
  [8] =
    {field_body, 4, .inherited = true},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 15,
  [18] = 16,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 20,
  [27] = 22,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '\n', 11,
        '\r', 12,
        '"', 18,
        '#', 13,
        '\'', 19,
        '\\', 6,
        '{', 16,
        '}', 17,
        '\t', 10,
        ' ', 10,
      );
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 11,
        '\r', 12,
        '"', 18,
        '\'', 19,
        '\\', 6,
        '}', 17,
        '\t', 10,
        ' ', 10,
      );
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(18);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(19);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(20);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(12);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym__hspace);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(11);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__atom);
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(3);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__atom);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(5);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__atom);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_single_quoted_string);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_double_quoted_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 8},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__hspace] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym__atom] = ACTIONS(1),
    [sym_single_quoted_string] = ACTIONS(1),
    [sym_double_quoted_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym__leading_spacing] = STATE(33),
    [sym__line_break] = STATE(13),
    [sym_rule] = STATE(14),
    [sym_rule_name] = STATE(23),
    [aux_sym_source_file_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__hspace] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [sym__atom] = ACTIONS(11),
  },
  [STATE(2)] = {
    [aux_sym__spacing] = STATE(4),
    [sym__space_unit] = STATE(4),
    [sym__line_break] = STATE(4),
    [sym_rule] = STATE(21),
    [sym__rule_body] = STATE(42),
    [sym__value] = STATE(21),
    [sym_rule_name] = STATE(23),
    [sym_literal] = STATE(21),
    [sym__hspace] = ACTIONS(13),
    [sym__newline] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(17),
    [sym__atom] = ACTIONS(19),
    [sym_single_quoted_string] = ACTIONS(21),
    [sym_double_quoted_string] = ACTIONS(21),
  },
  [STATE(3)] = {
    [aux_sym__spacing] = STATE(7),
    [sym__space_unit] = STATE(7),
    [sym__line_break] = STATE(7),
    [sym_rule] = STATE(21),
    [sym__rule_body] = STATE(41),
    [sym__value] = STATE(21),
    [sym_rule_name] = STATE(23),
    [sym_literal] = STATE(21),
    [sym__hspace] = ACTIONS(23),
    [sym__newline] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(25),
    [sym__atom] = ACTIONS(19),
    [sym_single_quoted_string] = ACTIONS(21),
    [sym_double_quoted_string] = ACTIONS(21),
  },
  [STATE(4)] = {
    [aux_sym__spacing] = STATE(7),
    [sym__space_unit] = STATE(7),
    [sym__line_break] = STATE(7),
    [sym_rule] = STATE(21),
    [sym__rule_body] = STATE(43),
    [sym__value] = STATE(21),
    [sym_rule_name] = STATE(23),
    [sym_literal] = STATE(21),
    [sym__hspace] = ACTIONS(23),
    [sym__newline] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym__atom] = ACTIONS(19),
    [sym_single_quoted_string] = ACTIONS(21),
    [sym_double_quoted_string] = ACTIONS(21),
  },
  [STATE(5)] = {
    [aux_sym__spacing] = STATE(6),
    [sym__space_unit] = STATE(6),
    [sym__line_break] = STATE(6),
    [sym_rule] = STATE(21),
    [sym__rule_body] = STATE(44),
    [sym__value] = STATE(21),
    [sym_rule_name] = STATE(23),
    [sym_literal] = STATE(21),
    [sym__hspace] = ACTIONS(29),
    [sym__newline] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym__atom] = ACTIONS(19),
    [sym_single_quoted_string] = ACTIONS(21),
    [sym_double_quoted_string] = ACTIONS(21),
  },
  [STATE(6)] = {
    [aux_sym__spacing] = STATE(7),
    [sym__space_unit] = STATE(7),
    [sym__line_break] = STATE(7),
    [sym_rule] = STATE(21),
    [sym__rule_body] = STATE(40),
    [sym__value] = STATE(21),
    [sym_rule_name] = STATE(23),
    [sym_literal] = STATE(21),
    [sym__hspace] = ACTIONS(23),
    [sym__newline] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(31),
    [sym__atom] = ACTIONS(19),
    [sym_single_quoted_string] = ACTIONS(21),
    [sym_double_quoted_string] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(33), 1,
      sym__hspace,
    ACTIONS(36), 1,
      sym__newline,
    ACTIONS(41), 1,
      sym__atom,
    ACTIONS(39), 3,
      anon_sym_RBRACE,
      sym_single_quoted_string,
      sym_double_quoted_string,
    STATE(7), 3,
      aux_sym__spacing,
      sym__space_unit,
      sym__line_break,
  [20] = 4,
    ACTIONS(43), 1,
      sym__hspace,
    ACTIONS(46), 1,
      sym__newline,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym__atom,
    STATE(8), 3,
      aux_sym__spacing,
      sym__space_unit,
      sym__line_break,
  [37] = 4,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(51), 1,
      sym__hspace,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      sym__atom,
    STATE(8), 3,
      aux_sym__spacing,
      sym__space_unit,
      sym__line_break,
  [53] = 4,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(55), 1,
      sym__hspace,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      sym__atom,
    STATE(9), 3,
      aux_sym__spacing,
      sym__space_unit,
      sym__line_break,
  [69] = 4,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(51), 1,
      sym__hspace,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      sym__atom,
    STATE(8), 3,
      aux_sym__spacing,
      sym__space_unit,
      sym__line_break,
  [85] = 4,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(51), 1,
      sym__hspace,
    ACTIONS(57), 2,
      ts_builtin_sym_end,
      sym__atom,
    STATE(8), 3,
      aux_sym__spacing,
      sym__space_unit,
      sym__line_break,
  [101] = 4,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(61), 1,
      sym__hspace,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      sym__atom,
    STATE(11), 3,
      aux_sym__spacing,
      sym__space_unit,
      sym__line_break,
  [117] = 4,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(65), 1,
      sym__hspace,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      sym__atom,
    STATE(12), 3,
      aux_sym__spacing,
      sym__space_unit,
      sym__line_break,
  [133] = 4,
    ACTIONS(67), 1,
      sym__hspace,
    ACTIONS(71), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym__atom,
    ACTIONS(69), 4,
      sym__newline,
      anon_sym_RBRACE,
      sym_single_quoted_string,
      sym_double_quoted_string,
  [149] = 3,
    ACTIONS(77), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym__atom,
    ACTIONS(75), 5,
      sym__hspace,
      sym__newline,
      anon_sym_RBRACE,
      sym_single_quoted_string,
      sym_double_quoted_string,
  [163] = 4,
    ACTIONS(73), 1,
      sym__atom,
    ACTIONS(81), 1,
      sym__hspace,
    ACTIONS(83), 1,
      sym_comment,
    ACTIONS(69), 3,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE,
  [178] = 3,
    ACTIONS(79), 1,
      sym__atom,
    ACTIONS(85), 1,
      sym_comment,
    ACTIONS(75), 4,
      ts_builtin_sym_end,
      sym__hspace,
      sym__newline,
      anon_sym_LBRACE,
  [191] = 4,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(51), 1,
      sym__hspace,
    ACTIONS(87), 1,
      anon_sym_LBRACE,
    STATE(8), 3,
      aux_sym__spacing,
      sym__space_unit,
      sym__line_break,
  [206] = 2,
    ACTIONS(79), 1,
      sym__atom,
    ACTIONS(75), 5,
      sym__hspace,
      sym__newline,
      anon_sym_RBRACE,
      sym_single_quoted_string,
      sym_double_quoted_string,
  [217] = 4,
    ACTIONS(15), 1,
      sym__newline,
    ACTIONS(89), 1,
      sym__hspace,
    ACTIONS(91), 1,
      anon_sym_RBRACE,
    STATE(3), 3,
      aux_sym__spacing,
      sym__space_unit,
      sym__line_break,
  [232] = 2,
    ACTIONS(95), 1,
      sym__atom,
    ACTIONS(93), 5,
      sym__hspace,
      sym__newline,
      anon_sym_RBRACE,
      sym_single_quoted_string,
      sym_double_quoted_string,
  [243] = 4,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(97), 1,
      sym__hspace,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    STATE(19), 3,
      aux_sym__spacing,
      sym__space_unit,
      sym__line_break,
  [258] = 5,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym__atom,
    STATE(10), 1,
      sym__line_break,
  [274] = 5,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 1,
      sym__atom,
    STATE(14), 1,
      sym_rule,
    STATE(23), 1,
      sym_rule_name,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
  [290] = 1,
    ACTIONS(75), 5,
      ts_builtin_sym_end,
      sym__hspace,
      sym__newline,
      anon_sym_LBRACE,
      sym__atom,
  [298] = 1,
    ACTIONS(93), 5,
      ts_builtin_sym_end,
      sym__hspace,
      sym__newline,
      anon_sym_LBRACE,
      sym__atom,
  [306] = 5,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    ACTIONS(110), 1,
      sym__atom,
    STATE(14), 1,
      sym_rule,
    STATE(23), 1,
      sym_rule_name,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
  [322] = 1,
    ACTIONS(112), 5,
      ts_builtin_sym_end,
      sym__hspace,
      sym__newline,
      anon_sym_RBRACE,
      sym__atom,
  [330] = 1,
    ACTIONS(114), 5,
      ts_builtin_sym_end,
      sym__hspace,
      sym__newline,
      anon_sym_RBRACE,
      sym__atom,
  [338] = 1,
    ACTIONS(116), 5,
      ts_builtin_sym_end,
      sym__hspace,
      sym__newline,
      anon_sym_RBRACE,
      sym__atom,
  [346] = 5,
    ACTIONS(110), 1,
      sym__atom,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      sym_rule,
    STATE(23), 1,
      sym_rule_name,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
  [362] = 5,
    ACTIONS(110), 1,
      sym__atom,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      sym_rule,
    STATE(23), 1,
      sym_rule_name,
    STATE(28), 1,
      aux_sym_source_file_repeat1,
  [378] = 1,
    ACTIONS(120), 5,
      ts_builtin_sym_end,
      sym__hspace,
      sym__newline,
      anon_sym_RBRACE,
      sym__atom,
  [386] = 1,
    ACTIONS(122), 5,
      ts_builtin_sym_end,
      sym__hspace,
      sym__newline,
      anon_sym_RBRACE,
      sym__atom,
  [394] = 1,
    ACTIONS(124), 5,
      ts_builtin_sym_end,
      sym__hspace,
      sym__newline,
      anon_sym_RBRACE,
      sym__atom,
  [402] = 1,
    ACTIONS(124), 5,
      ts_builtin_sym_end,
      sym__hspace,
      sym__newline,
      anon_sym_RBRACE,
      sym__atom,
  [410] = 3,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    ACTIONS(126), 2,
      sym__hspace,
      sym__newline,
  [421] = 1,
    ACTIONS(129), 3,
      sym__hspace,
      sym__newline,
      anon_sym_LBRACE,
  [427] = 1,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
  [431] = 1,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
  [435] = 1,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
  [439] = 1,
    ACTIONS(139), 1,
      anon_sym_RBRACE,
  [443] = 1,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
  [447] = 1,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 20,
  [SMALL_STATE(9)] = 37,
  [SMALL_STATE(10)] = 53,
  [SMALL_STATE(11)] = 69,
  [SMALL_STATE(12)] = 85,
  [SMALL_STATE(13)] = 101,
  [SMALL_STATE(14)] = 117,
  [SMALL_STATE(15)] = 133,
  [SMALL_STATE(16)] = 149,
  [SMALL_STATE(17)] = 163,
  [SMALL_STATE(18)] = 178,
  [SMALL_STATE(19)] = 191,
  [SMALL_STATE(20)] = 206,
  [SMALL_STATE(21)] = 217,
  [SMALL_STATE(22)] = 232,
  [SMALL_STATE(23)] = 243,
  [SMALL_STATE(24)] = 258,
  [SMALL_STATE(25)] = 274,
  [SMALL_STATE(26)] = 290,
  [SMALL_STATE(27)] = 298,
  [SMALL_STATE(28)] = 306,
  [SMALL_STATE(29)] = 322,
  [SMALL_STATE(30)] = 330,
  [SMALL_STATE(31)] = 338,
  [SMALL_STATE(32)] = 346,
  [SMALL_STATE(33)] = 362,
  [SMALL_STATE(34)] = 378,
  [SMALL_STATE(35)] = 386,
  [SMALL_STATE(36)] = 394,
  [SMALL_STATE(37)] = 402,
  [SMALL_STATE(38)] = 410,
  [SMALL_STATE(39)] = 421,
  [SMALL_STATE(40)] = 427,
  [SMALL_STATE(41)] = 431,
  [SMALL_STATE(42)] = 435,
  [SMALL_STATE(43)] = 439,
  [SMALL_STATE(44)] = 443,
  [SMALL_STATE(45)] = 447,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rule_body, 2, 0, 2),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__spacing, 2, 0, 0), SHIFT_REPEAT(7),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__spacing, 2, 0, 0), SHIFT_REPEAT(15),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__spacing, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__spacing, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__spacing, 2, 0, 0), SHIFT_REPEAT(8),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__spacing, 2, 0, 0), SHIFT_REPEAT(17),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__leading_spacing, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__leading_spacing, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__leading_spacing, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line_break, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line_break, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line_break, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line_break, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rule_body, 1, 0, 2),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line_break, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line_break, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__leading_spacing, 1, 0, 0),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, 0, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 6, 0, 6),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, 0, 4),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_rule_name, 1, 0, 0), REDUCE(sym_literal, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_name, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rule_body, 3, 0, 5),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [143] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_autark(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "autark",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 7,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
